### ISSUE TITLE
Library error

### ISSUE THREAD

**Issue by zorzansi** [volvox292/mass2smiles#2]
Hi,
I am trying to try the softare on cusatom data, but I get the following error:
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', 'app/mass2smiles_transformer.py', '22_s1_tassili_pos55-SE27_5ppm_MeOH50_1.mgf', '/app']' command failed.  (See above for error)
2023-09-12 15:27:30.890818: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-12 15:27:31.307795: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-09-12 15:27:31.307854: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-09-12 15:27:33.099684: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-09-12 15:27:33.099870: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-09-12 15:27:33.099915: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-09-12 15:32:45.403466: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-09-12 15:32:45.412014: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-09-12 15:32:45.414500: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (94fdfbb6efcb): /proc/driver/nvidia/version does not exist
2023-09-12 15:32:45.458108: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-12 15:32:45.498146: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 30382040 exceeds 10% of free system memory.

Could you help troubleshooting it?

I am running on Docker engine 24.0.6 on windows 10, configured to use Linux containers.

Thank you!

**Comment by volvox292** [comment]
Hi,

I think you are running out of RAM. How much do you have and how big is your dataset?

**Comment by zorzansi** [comment]
Indeed, docker was limited to 2GB RAM. I increased that to 24GB (I can go up to 50GB). The dataset is 150MB. It is running now, I will keep you updated. Thank you.

**Comment by zorzansi** [comment]
With 24GB RAM, after roughly two hours, I get the same error, but without any memory error reference:
`ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', 'app/mass2smiles_transformer.py', '22_s1_tassili_pos55-SE27_5ppm_MeOH50_1.mgf', '/app']' command failed.  (See above for error)
2023-09-13 10:21:53.477260: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-13 10:21:53.908345: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-09-13 10:21:53.908404: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-09-13 10:21:55.841109: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-09-13 10:21:55.841331: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-09-13 10:21:55.841372: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-09-13 10:26:56.769139: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-09-13 10:26:56.769664: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-09-13 10:26:56.769725: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (14231ffc9a19): /proc/driver/nvidia/version does not exist
2023-09-13 10:26:56.771550: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/opt/conda/envs/tf/.tmple9kkk39: line 3:    21 Killed                  python app/mass2smiles_transformer.py 22_s1_tassili_pos55-SE27_5ppm_MeOH50_1.mgf /app`

I do not have a GPU on this machine.

----- UPDATE-------
I pulled and run the doker on a machine with GPU, same 150MB file. Here is the error I got:
```
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', 'app/mass2smiles_transformer.py', './22_s1_tassili_pos55-SE27_5ppm_MeOH50_1.mgf', '/app']' command failed.  (See above for error)
2023-09-13 12:40:50.279165: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-13 12:40:50.397949: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-09-13 12:40:50.397982: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-09-13 12:40:51.216590: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-09-13 12:40:51.216673: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-09-13 12:40:51.216684: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-09-13 12:45:18.342082: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-09-13 12:45:18.342137: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-09-13 12:45:18.342178: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2023-09-13 12:45:18.342722: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "//app/mass2smiles_transformer.py", line 278, in <module>
    model.load_weights(os.path.normpath(sys.argv[2]+"/misunderstood-fire-207/model"))
  File "/opt/conda/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/conda/envs/tf/lib/python3.9/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 31, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /app/misunderstood-fire-207/model

parsing specs now
done!
encoding specs now
done!
TCN.receptive_field: 883.
```

**Please note that I am running delser292/mass2smiles:final and not mass2smiles:transformer_v1, which does not seem to be available for pull from docker.**
Any hint? Thank you!

**Comment by volvox292** [comment]
Hi,
I think it is not possible to run a 150 mb .mgf file with 50 gb of RAM.  This code is not designed for such big datasets. try to split your .mgf file. I think the biggest I run was a file with about 10-15k spectra and I think it already took 60 Gb of RAM. Also no need to use GPU, tensorflow GPU is not in the container anyway.

**Comment by zorzansi** [comment]
Hi,
the machine I am working with has 220GB of RAM, and I reduced the file to 1500 spectra (10MB). I get again the following error:
```
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', 'app/mass2smiles_transformer.py', './output.mgf', '/app']' command failed.  (See above for error)
parsing specs now
done!
encoding specs now
done!
TCN.receptive_field: 883.

2023-09-13 15:30:23.803170: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-13 15:30:24.002139: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-09-13 15:30:24.002171: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-09-13 15:30:24.873780: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-09-13 15:30:24.873865: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-09-13 15:30:24.873875: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-09-13 15:30:49.458837: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-09-13 15:30:49.458875: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-09-13 15:30:49.458909: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2023-09-13 15:30:49.459814: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "//app/mass2smiles_transformer.py", line 278, in <module>
    model.load_weights(os.path.normpath(sys.argv[2]+"/misunderstood-fire-207/model"))
  File "/opt/conda/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/conda/envs/tf/lib/python3.9/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 31, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /app/misunderstood-fire-207/model
```
What could it be? Thank you!

**Comment by volvox292** [comment]
Hi,
it seems the RAM issue is solved, but now there is a problem with loading the model. Did you download the models and place in the right directory? They should be placed as in the docker.zip file.

**Comment by zorzansi** [comment]
I pulled the container (delser292/mass2smiles:final and not mass2smiles:transformer_v1, which does not seem to be available for pull from docker) and copied the files in a folder called "~/MS/mass2smiles/" 
here is its content:
```
 myfile.mgf   predict_test_tanimoto_2out_v1_mf_docker.ipynb
 cddd_decode.py                               predict_test_tanimoto_2out_v1_mf.ipynb
 composite_math_v2_nist.py                    preprocessing_onlin-v3.ipynb
 composite_math_v2.py                         preprocessing_onlin-v3_mgf.ipynb
'docker.zip?download=1'                       preprocess_specs_16122022.ipynb
 feature_ids_dataframe.tsv                    README.md
 GPU_encode_smiles.py                         refine_code_17012023_train.json
 mass2smiles_transformer.py                   refine_code_17012023_valid.json
 molecularformula_casmi.ipynb                 substructure_1.1v.ipynb
 molecularformula.ipynb                       tcn_seq_train_hp.py
tcn_seq_train_used.py                            pos_encoding_visual.ipynb
```
Then I run: docker run -v ~/MS/mass2smiles/:/app  delser292/mass2smiles:final conda run -n tf python app/mass2smiles_transformer.py ./myfile.mgf /app

Shall I also download and unzip the docker.zip file in the same folder?

**Comment by volvox292** [comment]
The containers are exactly the same it is just a naming issue.
Yes you have to download and unzip, then just replace your mass2smiles folder with  the one from the zip and it should work.  The containers do not have  the models inside, so you can more easily retrain and switch models.

**Comment by zorzansi** [comment]
I confirm the software worked correctly after following the instructions in this thread. Thank you!
